spring.application.name=learnsync

spring.profiles.active=dev

# Config comun
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=false

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true

email.sender=${EMAIL:dev@example.com}
email.password=${PASSWORD:dev-password}
security.jwt.key.private=${SECRET_KEY:dev-secret-key-please-change-in-prod-min-32-chars}
security.jwt.user.generator=${USER_JWT:learnsync-dev}

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html

google.client.id=${GOOGLE_CLIENT_ID:dev-google-id}
imgur.bearer.token=${IMGUR_BEARER_TOKEN:dev-token}
imgur.api.url=${IMGUR_API_URL:https://api.imgur.com/3/image}
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS y URLs de frontend/backend
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}
app.backend.url=${BACKEND_URL:http://localhost:8080}
app.frontend.url=${FRONTEND_URL:http://localhost:4200}
