spring.application.name=learnsync

#spring.datasource.url=jdbc:postgresql://localhost:5432/learnsync

#spring.datasource.username=postgres
#spring.datasource.password=sysadmin
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none
# Cargar datos desde el archivo data.sql
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql

spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

email.sender= ${EMAIL}
email.password= ${PASSWORD}

security.jwt.key.private = ${SECRET_KEY}
security.jwt.user.generator = ${USER_JWT}

spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true

# Habilitar o Deshabilitar el Swagger-UI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Definir la ruta del Swagger
springdoc.swagger-ui.path=/doc/swagger-ui.html

google.client.id = ${GOOGLE_CLIENT_ID}

imgur.bearer.token=${IMGUR_BEARER_TOKEN}
imgur.api.url=${IMGUR_API_URL}
spring.servlet.multipart.enabled=true